/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Publisher;

import java.util.*;
import io.ably.lib.realtime.AblyRealtime;
import io.ably.lib.realtime.Channel;
import io.ably.lib.realtime.CompletionListener;
import io.ably.lib.types.AblyException;
import io.ably.lib.types.ErrorInfo;
import io.ably.lib.types.Message;

public class App {
   
    private final static String API_KEY = "INSERT"; /* Sign up at ably.io to get your API key */
    /* RuntimeException will be thrown if API_KEY will not be set to a proper one */
    static {
        if (API_KEY.contains("INSERT")) {
            throw new RuntimeException("API key is not set, sign up at ably.io to get yours");
        }
    }
    // Create a MPH String Array
    private static String[] MPH_ARRAY = {"180", "13", "55", "100", "160" };

    // Create a EngineTemp Array
    private static final String[] ENGINE_ARRAY = {"435", "234", "300", "342", "354"};

    // Create a TEMP Array
    private static final String[] TEMP_ARRAY = {"112.5", "100.0", "243.4", "121.2", "343.23"};

     // Create a GeForce Array
     private static final String[] GEFORCE_ARRAY = {"2.5", "1.0", "2.4", "-1.2", "3.23"};



    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
			initAbly();
		} catch (AblyException e) {
			//e.printStackTrace();
		}
    }

    public String getGreeting() {
        return "Starting Publisher...";
    }

    /* Add AblyException to method signature as AblyRealtime constructor can throw one */
	private static void initAbly() throws AblyException{
		AblyRealtime ablyRealtime = new AblyRealtime(API_KEY); 
       
        // Start of Publisher
        Channel channel = ablyRealtime.channels.get("START");     
        Date now = new Date();
        System.out.println("Publishing: " + now);
        channel.publish("update", "now: " + now, new CompletionListener() {
            @Override
            public void onSuccess() {
                /* Show success message when message is sent */
                System.out.println("Message sent: " + now);
            }

            @Override
            public void onError(ErrorInfo reason) {
                /* Show error message when something goes wrong */
            	System.out.println("Message not sent, error occurred: " + reason.message);
            }
        });

        // Start a threads

        Channel MPHchannel = ablyRealtime.channels.get("MPH");
        Channel ENGINEchannel = ablyRealtime.channels.get("ENGINE");
        Channel GEFORCEchannel = ablyRealtime.channels.get("MPH");

        // MPH Thread 1hz
        // Period in ms 100 equiv to 0.1hz
        Timer t0 = new Timer( );
        F1TimerTask tt0 = new F1TimerTask();
        tt0.NAME = "MPH";
        tt0.MESSAGES = MPH_ARRAY;
        tt0.ablyRealtime = ablyRealtime;
        t0.scheduleAtFixedRate(tt0,1000,100);

        // ENGINE Thread 1hz
        // Period in ms 500 equiv to 0.5hz
        Timer t1 = new Timer( );
        F1TimerTask tt1 = new F1TimerTask();
        tt1.NAME = "ENGINE";
        tt1.MESSAGES = ENGINE_ARRAY;
        tt1.ablyRealtime = ablyRealtime;
        t1.scheduleAtFixedRate(tt1,1000,500);

        // TEMP Thread 1hz
        // Period in ms 1000 equiv to 1hz
        Timer t2 = new Timer( );
        F1TimerTask tt2 = new F1TimerTask();
        tt2.NAME = "TEMP";
        tt2.MESSAGES = TEMP_ARRAY;
        tt2.ablyRealtime = ablyRealtime;
        t2.scheduleAtFixedRate(tt2,1000,1000);
         
        // GEFORCE Thread 1hz
        // Period in ms 50 equiv to .05hz
        Timer t3 = new Timer( );
        F1TimerTask tt3 = new F1TimerTask();
        tt3.NAME = "GEFORCE";
        tt3.MESSAGES = GEFORCE_ARRAY;
        tt3.ablyRealtime = ablyRealtime;
        t3.scheduleAtFixedRate(tt3,1000,50);

        // Prevent the app from quiting
        for (int i = 0; i < 1; ) {
            System.out.println("Main App Sleeping.." + i);
            try {
             Thread.sleep(50000000);
             ablyRealtime.close();
            } catch (InterruptedException e) {
             System.out.println("Thread has been interrupted");
            }
        }
         
	}

    
}
